"""Reproducible synthetic B2B distribution data and order-cohort metrics.

All SKUs and transactions are invented. No patient, prescription, or customer
records are accepted or generated by this example.
"""

from __future__ import annotations

import argparse
import csv
import json
import random
import sqlite3
from collections import defaultdict
from datetime import datetime, timedelta
from pathlib import Path


SEED = 20261006
AS_OF = "2026-10-06T23:59:59"
PRODUCTS = {"SYN-A": 1000, "SYN-B": 2000, "SYN-C": 3000, "SYN-D": 4000}
COLUMNS = {
    "order_lines": (
        "order_line_id", "order_id", "product_id", "order_at", "ordered_qty", "unit_price_krw"
    ),
    "shipment_lines": ("shipment_line_id", "order_line_id", "shipped_at", "shipped_qty"),
    "return_lines": (
        "return_line_id", "shipment_line_id", "returned_at", "recorded_at", "returned_qty"
    ),
    "inventory_snapshots": ("snapshot_at", "product_id", "on_hand_qty"),
}


def _at(day: datetime, hour: int = 9) -> str:
    return day.replace(hour=hour, minute=0, second=0).isoformat(timespec="seconds")


def generate_tables(seed: int = SEED) -> dict[str, list[dict[str, object]]]:
    rng = random.Random(seed)
    tables: dict[str, list[dict[str, object]]] = {name: [] for name in COLUMNS}
    orders = tables["order_lines"]
    shipments = tables["shipment_lines"]
    returns = tables["return_lines"]
    start = datetime(2026, 9, 1)

    # A transparent two-product example for manual reconciliation.
    orders.extend([
        {"order_line_id": "OL-0001", "order_id": "ORD-0001", "product_id": "SYN-A",
         "order_at": _at(start), "ordered_qty": 10, "unit_price_krw": 1000},
        {"order_line_id": "OL-0002", "order_id": "ORD-0001", "product_id": "SYN-B",
         "order_at": _at(start), "ordered_qty": 5, "unit_price_krw": 2000},
    ])
    shipments.extend([
        {"shipment_line_id": "SH-0001", "order_line_id": "OL-0001",
         "shipped_at": _at(start + timedelta(days=1)), "shipped_qty": 8},
        {"shipment_line_id": "SH-0002", "order_line_id": "OL-0002",
         "shipped_at": _at(start + timedelta(days=1)), "shipped_qty": 5},
    ])
    returns.append({"return_line_id": "RT-0001", "shipment_line_id": "SH-0002",
                    "returned_at": _at(start + timedelta(days=2)),
                    "recorded_at": _at(start + timedelta(days=3)), "returned_qty": 1})

    for day_index in range(20):
        order_day = start + timedelta(days=day_index)
        for local_order in range(2):
            order_number = 2 + day_index * 2 + local_order
            order_id = f"ORD-{order_number:04d}"
            product_ids = rng.sample(list(PRODUCTS), rng.randint(1, 3))
            for product_id in product_ids:
                line_number = len(orders) + 1
                line_id = f"OL-{line_number:04d}"
                quantity = rng.randint(3, 16)
                orders.append({"order_line_id": line_id, "order_id": order_id,
                               "product_id": product_id, "order_at": _at(order_day),
                               "ordered_qty": quantity, "unit_price_krw": PRODUCTS[product_id]})

                # One or two shipments, or an unfulfilled line. Sum never exceeds the order.
                shipped_total = rng.choice((0, quantity, quantity, rng.randint(1, quantity)))
                if shipped_total == 0:
                    continue
                split = rng.randint(1, shipped_total - 1) if shipped_total >= 4 and rng.random() < 0.35 else 0
                parts = (split, shipped_total - split) if split else (shipped_total,)
                for part_index, part_qty in enumerate(parts):
                    shipment_id = f"SH-{len(shipments) + 1:04d}"
                    ship_day = order_day + timedelta(days=1 + part_index + rng.randint(0, 2))
                    shipments.append({"shipment_line_id": shipment_id, "order_line_id": line_id,
                                      "shipped_at": _at(ship_day), "shipped_qty": part_qty})
                    if rng.random() < 0.18:
                        return_day = ship_day + timedelta(days=rng.randint(1, 5))
                        returns.append({"return_line_id": f"RT-{len(returns) + 1:04d}",
                                        "shipment_line_id": shipment_id,
                                        "returned_at": _at(return_day),
                                        "recorded_at": _at(return_day + timedelta(days=rng.randint(0, 3))),
                                        "returned_qty": rng.randint(1, part_qty)})

    # Inventory is an independent synthetic observation, not inferred from sales value.
    for snapshot_day in (datetime(2026, 9, 30), datetime(2026, 10, 6)):
        for product_id in PRODUCTS:
            tables["inventory_snapshots"].append({
                "snapshot_at": _at(snapshot_day, 23), "product_id": product_id,
                "on_hand_qty": rng.randint(20, 100),
            })
    validate_tables(tables)
    return tables


def validate_tables(tables: dict[str, list[dict[str, object]]]) -> None:
    """Reject broken grain, quantity, date, and cross-table references."""
    if set(tables) != set(COLUMNS):
        raise ValueError("table set mismatch")
    for name, rows in tables.items():
        for row in rows:
            if set(row) != set(COLUMNS[name]):
                raise ValueError(f"{name}: columns mismatch")

    def unique(rows: list[dict[str, object]], key: str) -> dict[str, dict[str, object]]:
        result = {str(row[key]): row for row in rows}
        if len(result) != len(rows):
            raise ValueError(f"duplicate {key}")
        return result

    orders = unique(tables["order_lines"], "order_line_id")
    shipments = unique(tables["shipment_lines"], "shipment_line_id")
    unique(tables["return_lines"], "return_line_id")
    snapshot_keys = [(str(r["snapshot_at"]), str(r["product_id"]))
                     for r in tables["inventory_snapshots"]]
    if len(set(snapshot_keys)) != len(snapshot_keys):
        raise ValueError("duplicate inventory snapshot")
    order_groups: dict[str, set[str]] = defaultdict(set)
    for row in orders.values():
        line_id = str(row["order_line_id"])
        product_id = str(row["product_id"])
        if product_id not in PRODUCTS or int(row["ordered_qty"]) <= 0 or int(row["unit_price_krw"]) < 0:
            raise ValueError(f"invalid order line {line_id}")
        datetime.fromisoformat(str(row["order_at"]))
        order_id = str(row["order_id"])
        if product_id in order_groups[order_id]:
            raise ValueError(f"duplicate product in order {order_id}")
        order_groups[order_id].add(product_id)

    shipped_by_line: dict[str, int] = defaultdict(int)
    returned_by_shipment: dict[str, int] = defaultdict(int)
    for row in shipments.values():
        line_id = str(row["order_line_id"])
        if line_id not in orders or int(row["shipped_qty"]) <= 0:
            raise ValueError("invalid shipment reference or quantity")
        if datetime.fromisoformat(str(row["shipped_at"])) < datetime.fromisoformat(str(orders[line_id]["order_at"])):
            raise ValueError("shipment before order")
        shipped_by_line[line_id] += int(row["shipped_qty"])
    for line_id, quantity in shipped_by_line.items():
        if quantity > int(orders[line_id]["ordered_qty"]):
            raise ValueError("shipment exceeds order")

    for row in tables["return_lines"]:
        shipment_id = str(row["shipment_line_id"])
        if shipment_id not in shipments or int(row["returned_qty"]) <= 0:
            raise ValueError("invalid return reference or quantity")
        shipped_at = datetime.fromisoformat(str(shipments[shipment_id]["shipped_at"]))
        returned_at = datetime.fromisoformat(str(row["returned_at"]))
        recorded_at = datetime.fromisoformat(str(row["recorded_at"]))
        if not shipped_at <= returned_at <= recorded_at:
            raise ValueError("invalid return dates")
        returned_by_shipment[shipment_id] += int(row["returned_qty"])
    for shipment_id, quantity in returned_by_shipment.items():
        if quantity > int(shipments[shipment_id]["shipped_qty"]):
            raise ValueError("return exceeds shipment")
    for row in tables["inventory_snapshots"]:
        datetime.fromisoformat(str(row["snapshot_at"]))
        if str(row["product_id"]) not in PRODUCTS or int(row["on_hand_qty"]) < 0:
            raise ValueError("invalid inventory snapshot")


def write_tables(tables: dict[str, list[dict[str, object]]], directory: Path) -> None:
    directory.mkdir(parents=True, exist_ok=True)
    for name, columns in COLUMNS.items():
        with (directory / f"{name}.csv").open("w", encoding="utf-8", newline="") as handle:
            writer = csv.DictWriter(handle, fieldnames=columns, lineterminator="\n")
            writer.writeheader()
            writer.writerows(tables[name])


def read_tables(directory: Path) -> dict[str, list[dict[str, object]]]:
    tables: dict[str, list[dict[str, object]]] = {}
    for name, columns in COLUMNS.items():
        with (directory / f"{name}.csv").open("r", encoding="utf-8", newline="") as handle:
            reader = csv.DictReader(handle)
            if tuple(reader.fieldnames or ()) != columns:
                raise ValueError(f"{name}: unexpected CSV header")
            tables[name] = list(reader)
    validate_tables(tables)
    return tables


QUERY = """
WITH shipped AS (
  SELECT order_line_id, SUM(shipped_qty) AS qty
  FROM shipment_lines WHERE shipped_at <= :as_of GROUP BY order_line_id
), returned AS (
  SELECT s.order_line_id, SUM(r.returned_qty) AS qty
  FROM return_lines r JOIN shipment_lines s USING (shipment_line_id)
  WHERE r.recorded_at <= :as_of GROUP BY s.order_line_id
)
SELECT substr(o.order_at, 1, 10) AS order_date, o.product_id,
       SUM(o.ordered_qty) AS ordered_qty,
       SUM(o.ordered_qty * o.unit_price_krw) AS ordered_value_krw,
       SUM(COALESCE(s.qty, 0)) AS shipped_qty,
       SUM(COALESCE(s.qty, 0) * o.unit_price_krw) AS shipped_value_krw,
       SUM(COALESCE(r.qty, 0)) AS returned_qty,
       SUM(COALESCE(r.qty, 0) * o.unit_price_krw) AS returned_value_krw
FROM order_lines o
LEFT JOIN shipped s USING (order_line_id)
LEFT JOIN returned r USING (order_line_id)
WHERE o.order_at <= :as_of
GROUP BY order_date, o.product_id ORDER BY order_date, o.product_id
"""


def analyze(tables: dict[str, list[dict[str, object]]], as_of: str = AS_OF) -> tuple[list[dict], dict]:
    validate_tables(tables)
    datetime.fromisoformat(as_of)
    with sqlite3.connect(":memory:") as db:
        db.row_factory = sqlite3.Row
        db.executescript("""
            CREATE TABLE order_lines (order_line_id TEXT PRIMARY KEY, order_id TEXT,
              product_id TEXT, order_at TEXT, ordered_qty INTEGER, unit_price_krw INTEGER);
            CREATE TABLE shipment_lines (shipment_line_id TEXT PRIMARY KEY,
              order_line_id TEXT, shipped_at TEXT, shipped_qty INTEGER);
            CREATE TABLE return_lines (return_line_id TEXT PRIMARY KEY, shipment_line_id TEXT,
              returned_at TEXT, recorded_at TEXT, returned_qty INTEGER);
        """)
        for name in ("order_lines", "shipment_lines", "return_lines"):
            columns = COLUMNS[name]
            placeholders = ",".join("?" for _ in columns)
            db.executemany(f"INSERT INTO {name} VALUES ({placeholders})",
                           [[row[column] for column in columns] for row in tables[name]])
        rows = [dict(row) for row in db.execute(QUERY, {"as_of": as_of})]

    for row in rows:
        row["net_shipped_value_krw"] = row["shipped_value_krw"] - row["returned_value_krw"]
        row["fulfillment_rate"] = round(row["shipped_qty"] / row["ordered_qty"], 4)
    quantity_fields = ("ordered_qty", "shipped_qty", "returned_qty")
    value_fields = ("ordered_value_krw", "shipped_value_krw", "returned_value_krw",
                    "net_shipped_value_krw")
    summary = {key: sum(row[key] for row in rows) for key in (*quantity_fields, *value_fields)}
    summary["as_of"] = as_of
    summary["fulfillment_rate"] = (
        round(summary["shipped_qty"] / summary["ordered_qty"], 4)
        if summary["ordered_qty"] else None
    )
    summary["order_line_count"] = sum(
        str(row["order_at"]) <= as_of for row in tables["order_lines"]
    )
    return rows, summary


def write_analysis(rows: list[dict], summary: dict, directory: Path) -> None:
    directory.mkdir(parents=True, exist_ok=True)
    columns = ("order_date", "product_id", "ordered_qty", "ordered_value_krw",
               "shipped_qty", "shipped_value_krw", "returned_qty",
               "returned_value_krw", "net_shipped_value_krw", "fulfillment_rate")
    with (directory / "daily_product_metrics.csv").open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=columns, lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)
    (directory / "summary.json").write_text(
        json.dumps(summary, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    command = parser.add_subparsers(dest="command", required=True)
    generate = command.add_parser("generate", help="write deterministic synthetic CSVs")
    generate.add_argument("--output", type=Path, required=True)
    run_analysis = command.add_parser("analyze", help="validate CSVs and compute order-cohort metrics")
    run_analysis.add_argument("--input", type=Path, required=True)
    run_analysis.add_argument("--output", type=Path, required=True)
    run_analysis.add_argument("--as-of", default=AS_OF)
    args = parser.parse_args()
    if args.command == "generate":
        tables = generate_tables()
        write_tables(tables, args.output)
        print(json.dumps({name: len(rows) for name, rows in tables.items()}))
    else:
        rows, summary = analyze(read_tables(args.input), args.as_of)
        write_analysis(rows, summary, args.output)
        print(json.dumps(summary, ensure_ascii=False, sort_keys=True))


if __name__ == "__main__":
    main()
